### ISSUE TITLE
`lein dev` fails with no such file or directory error.

### ISSUE THREAD

**Issue by aeberts** [binaryage/dirac-sample#4]
Hi!
I'm running the dirac-sample to get a feel for how to set it up with my own project and the project.clj is more complicated than I'm used to so my apologies if this is a "user error". 

When running `dirac-sample` using `lein dev` the compile fails with the following error:

```
dirac-sample git:(master) ✗ lein dev
17:54:37 server   | Starting HTTP server on port 9977 => http://localhost:9977
17:54:37 figwheel | Figwheel: Cutting some fruit, just a sec ...
17:54:53 figwheel | Figwheel: Validating the configuration found in project.clj
17:54:53 figwheel | Figwheel: Configuration Valid ;)
17:54:53 figwheel | Figwheel: Starting server at http://0.0.0.0:7111
17:54:53 figwheel | Figwheel: Watching build - demo
17:54:53 figwheel | Figwheel: Cleaning build - demo
17:54:53 figwheel | Compiling "resources/public/.compiled/demo/demo.js" from ("src/shared" "src/demo" "checkouts/cljs-devtools/src/lib" "checkouts/dirac/src/runtime")...
17:54:53 figwheel | Failed to compile "resources/public/.compiled/demo/demo.js" in 0.184 seconds.
17:54:53 figwheel | ----  Exception    ----
17:54:53 figwheel | 
17:54:53 figwheel |   checkouts/cljs-devtools/src/lib (No such file or directory)
17:54:53 figwheel | 
17:54:53 figwheel | ----  Exception Stack Trace  ----
17:54:53 figwheel | 
17:54:53 figwheel | java.io.FileNotFoundException: checkouts/cljs-devtools/src/lib (No such file or directory)
17:54:53 figwheel |  at java.io.FileInputStream.open (FileInputStream.java:-2)
17:54:53 figwheel |     java.io.FileInputStream.<init> (FileInputStream.java:138)
17:54:53 figwheel |     clojure.java.io$fn__10768.invokeStatic (io.clj:229)
17:54:53 figwheel |     clojure.java.io/fn (io.clj:229)
```

Unfortunately, I don't know enough about checkouts to be able to give you any suggestions on how to debug the issue. Happy to help if you need more info.

**Comment by darwin** [comment]
Why do you run `lein dev`? The task is for me when developing dirac-sample and want to test it against [checkouts](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies) of dirac and cljs-devtools libraries.

You are right, unfortunately `project.clj` is quite complicated because I have there some tests and dev-cases so I can test them from time to time myself on a "real" project. Maybe in the future I should split the two. Keep only minimalist example project and maintain another test project for development tasks.

To test-drive dirac via dirac-sample please follow the readme:
https://github.com/binaryage/dirac-sample
